### ISSUE TITLE
Samples per epoch

### ISSUE THREAD

**Issue by MosMK** [ZFTurbo/Kaggle-Planet-Understanding-the-Amazon-from-Space#1]
Thank you so much.
Can i ask why did you choose around 10% of train data for each epoch?

**Comment by ZFTurbo** [comment]
You can change it to any other value. Most common is to use ~100% of data per epoch. I just wanted to track progress of training at higher rate.

**Comment by MosMK** [comment]
So you actually used the 10% during training and it didn't affect the performance of your models?

**Comment by ZFTurbo** [comment]
No. I used all the data. I just used random 10% subsample of available data per epoch.

**Comment by MosMK** [comment]
Thank you.
